"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.kosenList = void 0;
exports.kosenList = [
    // 北海道地方
    {
        id: 'hakodate',
        name: '函館工業高等専門学校',
        yomi: 'はこだてこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '北海道',
        website: 'https://www.hakodate-ct.ac.jp/',
        departments: [
            '生産システム工学科',
            '機械・社会基盤工学系',
            '電気電子・情報工学系',
        ],
        description: '北海道函館市に位置する国立高等専門学校。3つの学科を有し、実践的な技術者教育を提供。幅広い分野で活躍できる人材の育成を目指しており、地域社会や産業界との連携も強い。',
        latitude: 41.838,
        longitude: 140.767,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Bldg.Advanced-course_of_NIT%2C_Hakodate_College.jpg',
        imageCreditText: 'Itya, CC0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Bldg.Advanced-course_of_NIT,_Hakodate_College.jpg',
        detailedDescription: '函館高専は1962年に設立され、「自由闊達、創造性豊かな人材」「幅広い教養と豊かな人間性を備えた人材」「科学技術の専門的素養と自主的・実践的な行動力を備えた人材」の育成を教育目的としています。生産システム工学科は、機械・社会基盤系と電気電子・情報系の2つの系から構成され、1〜2年次は共通カリキュラムで基礎を学び、3年次から専門分野に分かれる教育システムを採用しています。グローバルマインドの育成に力を入れており、国際寮の設置や海外インターンシップ、協定校との交換留学など国際交流プログラムが充実。また、地域連携も活発で、函館市や地元企業との共同研究、地域課題解決プロジェクトなどを通じて実践的な教育を展開しています。特に環境・エネルギー分野や情報技術、社会インフラに関する研究が盛んで、地域の産業振興に貢献。キャンパスは函館湾を一望できる高台に位置し、自然環境に恵まれた学習環境が整っています。',
    },
    {
        id: 'tomakomai',
        name: '苫小牧工業高等専門学校',
        yomi: 'とまこまいこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '北海道',
        website: 'https://www.tomakomai-ct.ac.jp/',
        departments: [
            '創造工学科',
            '機械・電気系',
            '物質・環境系',
            '情報・ソフトウェア系',
        ],
        description: '北海道苫小牧市にある国立高等専門学校。1学科4系制で、分野横断的な学習が可能。産業都市苫小牧の特性を活かし、企業との連携による実践的な教育プログラムが充実している。',
        latitude: 42.658,
        longitude: 141.637,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c9/National_Institute_of_Technology%2CTomakomai_College.jpg',
        imageCreditText: 'Endou subaru, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:National_Institute_of_Technology,Tomakomai_College.jpg',
        detailedDescription: '苫小牧高専は、特徴的な「1学科5系」システムを採用し、1年次は共通教育で工学の基礎を学び、2年次から機械系、都市・環境系、応用化学・生物系、電気電子系、情報科学・工学系の5つの専門系に分かれます。この教育システムにより、学生は自分の適性をじっくり見極めてから専門分野を選択できます。4年次からは専門を深める「系専門コース」と、工学にマネジメント系科目を融合させた「フロンティアコース」に分かれ、次世代のイノベーション人材を育成。独自科目「創造工学」では課題解決型学習を通じて創造性を育み、「AIデータサイエンス」では全学生が数理・データサイエンス・AIの基礎を学びます。豊かな人間性と自主自律の精神を育成し、社会の発展に貢献できる実践的技術者の育成を教育理念としています。苫小牧の産業界との強い連携により、実践的な教育プログラムが充実しており、グローバルな視点を持つ技術者を育成しています。',
    },
    {
        id: 'kushiro',
        name: '釧路工業高等専門学校',
        yomi: 'くしろこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '北海道',
        website: 'https://www.kushiro-ct.ac.jp/',
        departments: [
            '創造工学科',
            'スマートメカニクスコース',
            'エレクトロニクスコース',
            'マテリアル・バイオコース',
            '情報・アーキテクチャコース',
        ],
        description: '北海道釧路市に位置する国立高専。1学科4コース制で、学生の興味に応じた専門分野を深く学べる。豊かな自然環境を活かした研究や、国際交流にも力を入れている。',
        latitude: 43.033,
        longitude: 144.407,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/94/Kushiro_national_college_of_technology.jpg',
        imageCreditText: 'GenOishi, Public domain, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Kushiro_national_college_of_technology.jpg',
        detailedDescription: '釧路高専は、東北海道に位置する高等技術教育機関として、「創造性と問題発見・解決能力を身につけた実践的技術者の育成」を教育理念に掲げています。創造工学科には、スマートメカニクスコース（機械工学）、エレクトロニクスコース（電気・電子工学）、マテリアル・バイオコース（物質工学）、情報・アーキテクチャコース（情報工学・建築学）の4コースを設置。機械が好きで新しいものづくりに挑戦したい人、人のために役立ち地球に優しいものづくりに関心のある人、グローバルな視点で安全なものづくりに貢献したい人を求めています。教育目標として、豊かな人格形成、幅広い視野を持つ創造的技術者の育成、進取の精神の涵養を掲げ、地域産業への貢献、国内外で活躍できる技術者の育成、産業界への技術支援、技術者のキャリアアップ教育、地域住民の生涯学習支援などを使命としています。豊かな自然環境を活かした教育研究活動と地域連携が特徴です。',
    },
    {
        id: 'asahikawa',
        name: '旭川工業高等専門学校',
        yomi: 'あさひかわこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '北海道',
        website: 'https://www.asahikawa-ct.ac.jp/',
        departments: [
            '創造工学科',
            'スマートメカニクス学科',
            'エレクトロニクス学科',
            'マテリアル・バイオ学科',
            '情報・アーキテクチャ学科',
        ],
        description: '北海道旭川市に位置する国立高等専門学校。1学科4分野の構成で、幅広い工学分野の知識と技術を習得できる。地域産業との連携を重視し、実践的な技術者を育成している。',
        latitude: 43.784,
        longitude: 142.428,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/48/Asahikawa-NCT_201105.jpg',
        imageCreditText: 'Rela1470, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Asahikawa-NCT_201105.jpg',
        detailedDescription: '旭川高専は「自由活発に学び育つ、国際的視野と人間性に富んだ実践的な技術を手に入れる」ことを目標に、斬新なアイディアを発信し意義ある価値を創造できる、社会的・科学的・技術的な変革をもたらそうとする気概を有した人材の育成を目指しています。令和8年度から学科改組を予定しており、スマートメカニクス系、エレクトロニクス系、マテリアル・バイオ系、情報・アーキテクチャ系の4系体制で専門教育を展開。グローバル化を目指した国際交流プログラムとして、留学生の積極的な受け入れ、International Commonsなどの国際交流イベント、海外の教育機関との連携を推進。また、半導体関連企業との産学連携授業、数理・データサイエンス・AI教育、地域企業との共同研究など、地元に根差しながら国際的な視野を持つ技術者の育成に力を注いでいます。旭川ウェルビーイング・コンソーシアムなど地域連携も活発で、産学官による地場産業の活性化に貢献しています。',
    },
    // 東北地方
    {
        id: 'hachinohe',
        name: '八戸工業高等専門学校',
        yomi: 'はちのへこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '東北',
        website: 'https://www.hachinohe-ct.ac.jp/',
        departments: ['産業システム工学科'],
        description: '青森県八戸市に位置する国立高等専門学校。産業システム工学科という1学科の中に4つのコースがあり、それぞれの専門性を深めながら、複合的な領域も学べる教育を展開している。',
        latitude: 40.54,
        longitude: 141.455,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/National_Institute_of_Technology_Hachinohe_College.jpg',
        imageCreditText: 'Mochizuki1018, CC BY 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:National_Institute_of_Technology_Hachinohe_College.jpg',
        detailedDescription: '八戸高専は昭和38年に設立され、「誠実・進取・協調」の校訓のもと、創造力豊かな実践的技術者の育成を目指しています。平成27年度に従来の4学科を産業システム工学科1学科に統合し、機械・医工学、電気情報工学、マテリアル・バイオ工学、環境都市・建築デザインの4コース制を採用。特徴的な教育プログラムとして「自主探究」を正式カリキュラムに組み込み、1～3年生が自ら課題を発見し解決策を探る活動を実施。全国初の4学期制（春夏秋冬）を導入し、学習の集中度を高めるとともに自主探究活動の時間を確保。グローバルエンジニア教育にも力を入れ、シンガポールやモンゴルなどでの海外研修、TOEICの積極的活用により、専攻科修了時の平均スコアは600点を超えています。中学3年の9月に推薦入試を実施する特別選抜制度も導入。地域連携では防災技術研究や地元企業との共同研究が活発で、全人格形成を重視した教育寮も特徴的です。',
    },
    {
        id: 'ichinoseki',
        name: '一関工業高等専門学校',
        yomi: 'いちのせきこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '東北',
        website: 'https://www.ichinoseki.ac.jp/',
        departments: ['未来創造工学科'],
        description: '岩手県一関市に位置する国立高等専門学校。未来創造工学科に4つの専門コースを設け、分野横断的な教育を実施。地域連携やグローバル教育にも力を入れている。',
        latitude: 38.932,
        longitude: 141.16,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/National_Institute_of_Technology%2C_Ichinoseki_College_1.jpg',
        imageCreditText: 'Ebiebi2, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:National_Institute_of_Technology,_Ichinoseki_College_1.jpg',
        detailedDescription: '一関高専は1964年に設立され、「明日を拓く創造性豊かな実践的技術者の育成」を教育理念に掲げています。平成29年度に従来の4学科を統合し、「未来創造工学科」を設置。機械・知能系、電気・電子系、情報・ソフトウェア系、化学・バイオ系の4系・7分野構成で、1年次は共通教育、2年進級時に専門系を選択する柔軟な教育システムを採用。教育目標として、国際社会で活動できる技術者、誠実で豊かな人間性と広い視野を持つ技術者、優れた創造力・開発力を持つ技術者などの育成を掲げています。日本技術者教育認定機構（JABEE）認定の「生産技術情報システム工学」教育プログラムを実施し、本科4年から専攻科までの4年間で高度な技術者教育を提供。岩手県南技術研究センターとの連携協定を締結し、地域産業の発展に貢献。高専ロボコンでは第5回大会（1992年）優勝の「ころころ君」、第25回大会（2012年）優勝の「椀子兄弟」、第31回大会（2018年）優勝の「一角」と3度の全国制覇を達成しています。',
    },
    {
        id: 'sendai',
        name: '仙台高等専門学校',
        yomi: 'せんだいこうとうせんもんがっこう',
        type: '国立',
        campus: '広瀬キャンパス',
        region: '東北',
        website: 'https://www.sendai-nct.ac.jp/',
        departments: [
            '未来イノベーション工学系',
            '機械・知能コース',
            '電気・電子コース',
            '情報・ネットワークコース',
        ],
        description: '宮城県仙台市に位置する国立高等専門学校。広瀬、名取の2キャンパス体制。広瀬キャンパスは情報・電子・機械分野が中心。社会のニーズに応える革新的な技術者の育成を目指している。',
        latitude: 38.288,
        longitude: 140.78,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/SNCT-Hirose.jpg',
        imageCreditText: 'Koho snct, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://ja.wikipedia.org/wiki/File:SNCT-Hirose.jpg',
        detailedDescription: '仙台高等専門学校は、仙台（広瀬）と名取の2つのキャンパスを持つ国立高等専門学校で、2009年に仙台電波工業高等専門学校と宮城工業高等専門学校が統合・再編されて誕生しました。広瀬キャンパスは旧仙台電波高専を母体とし、情報・電子・機械分野に重点を置いています。1学科3コース制（機械・知能コース、電気・電子コース、情報・ネットワークコース）で専門分野を深く学べます。「未来イノベーション工学系」として2キャンパスが連携し、幅広い工学分野の知識と技術を統合した教育を展開。グローバルな視野を持ち、社会が直面する課題を解決できる革新的な技術者の育成を目指しています。学生の自主性を重んじ、ロボコンやプロコンなどの課外活動も活発で、多くの学生が全国レベルで活躍しています。',
    },
    {
        id: 'sendai-natori',
        name: '仙台高等専門学校',
        yomi: 'せんだいこうとうせんもんがっこう',
        type: '国立',
        campus: '名取キャンパス',
        region: '東北',
        website: 'https://www.sendai-nct.ac.jp/',
        departments: [
            '未来イノベーション工学系',
            'マテリアル・バイオコース',
            '建築・デザインコース',
        ],
        description: '宮城県名取市に位置する国立高等専門学校。名取キャンパスは、建築、デザイン、応用科学分野に強みを持つ。広瀬キャンパスと連携し、幅広い分野の技術者を育成している。',
        latitude: 38.169,
        longitude: 140.892,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Sendai_Kosen_in_Natori_2011.jpg',
        imageCreditText: 'Kinori, CC0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Sendai_Kosen_in_Natori_2011.jpg',
        detailedDescription: '仙台高等専門学校の名取キャンパスは、旧宮城高専を母体とし、建築、デザイン、応用科学（マテリアル・バイオ）分野に強みを持っています。「未来イノベーション工学系」として広瀬キャンパスと連携し、複合的な視点からものづくりを探求できる教育環境が特徴です。1学科2コース制（マテリアル・バイオコース、建築・デザインコース）で、持続可能な社会の実現に貢献する技術者の育成に注力しています。実験・実習を重視したカリキュラムを通じて、実践的な問題解決能力を養います。地域企業との共同研究やインターンシップも盛んで、地域社会の発展に貢献する人材を輩出しています。',
    },
    {
        id: 'akita',
        name: '秋田工業高等専門学校',
        yomi: 'あきたこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '東北',
        website: 'https://www.akita-nct.ac.jp/',
        departments: ['創造システム工学科'],
        description: '秋田県秋田市に位置する国立高等専門学校。1学科4コース制で、幅広い工学分野をカバー。新技術の開発や地域産業の発展に貢献する人材を育成している。',
        latitude: 39.718,
        longitude: 140.05,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b6/National_Institute_of_Technology%2C_Akita_College_20181103.jpg',
        imageCreditText: '掬茶, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:National_Institute_of_Technology,_Akita_College_20181103.jpg',
        detailedDescription: '秋田工業高等専門学校は、1964年に設立された秋田県秋田市に位置する国立高等専門学校です。「進取」「創造」「協力」を校訓とし、社会の発展に貢献できる実践的技術者の育成を目指しています。2010年度より、従来の4学科を「創造システム工学科」1学科に統合し、学生の多様な興味や進路に対応するコース制を導入しました。この体制により、学生は幅広い工学分野の基礎を学んだ上で、自身の専門性を深めていくことが可能です。特に、再生可能エネルギー分野や地域産業と連携した実践的な教育・研究に力を入れています。複合的な視点と問題解決能力を養うためのPBL（Project Based Learning）型授業も積極的に取り入れられており、学生の主体的な学びを促進しています。',
    },
    {
        id: 'tsuruoka',
        name: '鶴岡工業高等専門学校',
        yomi: 'つるおかこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '東北',
        website: 'https://www.tsuruoka-nct.ac.jp/',
        departments: ['創造工学科'],
        description: '山形県鶴岡市に位置する国立高等専門学校。創造工学科に4つの専門コースを設置。地域企業との共同研究や、バイオ分野の研究が盛ん。グローバルな視点を持つ技術者を育成する。',
        latitude: 38.736,
        longitude: 139.816,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Tsuruoka-nct.jpg',
        imageCreditText: 'Abentz, CC BY 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Tsuruoka-nct.jpg',
        detailedDescription: '鶴岡工業高等専門学校は、1963年に設立された山形県鶴岡市に位置する国立高等専門学校です。「自主・自律・自由」の精神を尊重し、豊かな人間性と国際感覚を備えた創造的技術者の育成を教育理念としています。2017年度から、従来の4学科を「創造工学科」1学科に再編し、4つの専門コースを設置する体制に移行しました。このコース制により、学生は幅広い工学の基礎知識を身につけた後、自身の関心に応じて専門分野を選択し、深く学ぶことができます。特に、世界的なバイオサイエンスの拠点である鶴岡市の立地を活かし、バイオ分野の研究・教育に力を入れているのが大きな特徴です。地域企業との共同研究やインターンシップも活発で、地域創生に貢献する実践的な技術者を輩出しています。',
    },
    {
        id: 'fukushima',
        name: '福島工業高等専門学校',
        yomi: 'ふくしまこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '東北',
        website: 'https://www.fukushima-nct.ac.jp/',
        departments: [
            '機械システム工学科',
            '電気電子システム工学科',
            '化学・バイオ工学科',
            '都市システム工学科',
            'ビジネスコミュニケーション学科',
        ],
        description: '福島県いわき市に位置する国立高等専門学校。工学系4学科に加え、文系のビジネスコミュニケーション学科を持つユニークな構成。複合的な知識を持つ人材を育成している。',
        latitude: 36.953,
        longitude: 140.871,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Fukushima_National_College_of_Technology.JPG',
        imageCreditText: 'Altomarina, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Fukushima_National_College_of_Technology.JPG',
        detailedDescription: '福島工業高等専門学校は、福島県いわき市に位置する国立高等専門学校です。最大の特徴は、工学系の4学科（機械システム工学科、電気電子システム工学科、化学・バイオ工学科、都市システム工学科）に加えて、全国の高専で唯一、文系の「ビジネスコミュニケーション学科」を設置している点です。このユニークな学科構成により、技術的な専門知識と、語学力やプレゼンテーション能力、経済学・経営学の素養といったコミュニケーション能力を兼ね備えた、複合的な視野を持つ人材の育成を目指しています。東日本大震災からの復興に貢献するため、再生可能エネルギーや防災・減災、廃炉技術などの分野にも力を入れています。学生のキャリアデザイン教育にも注力しており、インターンシップや地域連携活動を通じて、社会で活躍するための実践力を養います。',
    },
    // 関東信越地方
    {
        id: 'ibaraki',
        name: '茨城工業高等専門学校',
        yomi: 'いばらきこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '関東信越',
        website: 'https://www.ibaraki-ct.ac.jp/',
        departments: ['国際創造工学科'],
        description: '茨城県ひたちなか市にある国立高等専門学校。国際創造工学科の中に複数の専門分野があり、グローバルな視点と創造性を持った技術者の育成に力を入れている。',
        latitude: 36.398,
        longitude: 140.548,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Ibaraki_National_College_of_Technology.JPG',
        imageCreditText: 'Abasaa, Public domain, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Ibaraki_National_College_of_Technology.JPG',
        detailedDescription: '茨城工業高等専門学校は、1964年に設立された茨城県ひたちなか市に位置する国立高等専門学校です。「優れた人格と国際性を備え、未来を拓く創造性豊かな実践的技術者の育成」を教育理念に掲げています。2016年度に、従来の4学科を「国際創造工学科」1学科に統合し、グローバル社会で活躍できる技術者の育成に特化した教育を行っています。低学年から英語による科学技術教育やPBL型授業を導入し、実践的なコミュニケーション能力と問題解決能力を養います。4年次には、全ての学生が海外研修に参加する「グローバルエンジニアリング研修」が必修となっており、国際感覚を磨く機会が豊富に用意されています。JICAとの連携や、近隣の研究機関・企業との共同研究も盛んで、地域に根ざしながら世界で活躍する人材を輩出しています。',
    },
    {
        id: 'oyama',
        name: '小山工業高等専門学校',
        yomi: 'おやまこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '関東信越',
        website: 'https://www.oyama-ct.ac.jp/',
        departments: [
            '機械工学科',
            '電気電子創造工学科',
            '物質工学科',
            '建築学科',
        ],
        description: '栃木県小山市にある国立高等専門学校。4つの専門学科を設置し、各分野で高い専門性を持つ技術者を育成。地域産業界との連携による実践的な教育が特徴。',
        latitude: 36.279,
        longitude: 139.799,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Oyama_National_College_of_Technology_main_gate.JPG',
        imageCreditText: 'ほぶ, CC0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Oyama_National_College_of_Technology_main_gate.JPG',
        detailedDescription: '小山工業高等専門学校は、1965年に設立された栃木県小山市に位置する国立高等専門学校です。「技術者である前に人間であれ」という理念のもと、豊かな人間性と高い倫理観を備えた技術者の育成を重視しています。機械工学科、電気電子創造工学科、物質工学科、建築学科の4つの専門学科を設置し、それぞれの分野で基礎から応用までを体系的に学ぶことができます。特に、複合的な視点を養うための学科横断的な教育プログラムや、地域企業と連携した課題解決型学習（PBL）が充実しています。学生の自主性を尊重する校風で、ロボットコンテストやプログラミングコンテストなどの全国大会で優秀な成績を収めています。卒業生の多くは地域産業界の中核を担う技術者として活躍しており、企業からの信頼も厚い学校です。',
    },
    {
        id: 'gunma',
        name: '群馬工業高等専門学校',
        yomi: 'ぐんまこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '関東信越',
        website: 'https://www.gunma-ct.ac.jp/',
        departments: [
            '機械工学科',
            '電子メディア工学科',
            '電子情報工学科',
            '物質・生物工学科',
            '環境都市工学科',
        ],
        description: '群馬県前橋市にある国立高等専門学校。5つの学科があり、幅広い工学分野を網羅。学生の主体的な学びを促す教育プログラムと、充実した研究設備が強み。',
        latitude: 36.417,
        longitude: 139.096,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Gunma_National_College_of_Technology.jpg',
        imageCreditText: '☆(・ω<), CC BY 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Gunma_National_College_of_Technology.jpg',
        detailedDescription: '群馬工業高等専門学校は、1962年に設立された群馬県前橋市に位置する国立高等専門学校です。「人間性を尊重し、個性豊かな創造性あふれる実践的技術者を育成する」ことを教育理念としています。機械工学科、電子メディア工学科、電子情報工学科、物質・生物工学科、環境都市工学科の5つの専門学科を設置し、幅広い工学分野を網羅しています。低学年から専門科目を導入し、早期に専門意識を高めるとともに、実験・実習を重視したカリキュラムで実践力を養います。学生の自主的な研究活動を支援する体制が整っており、充実した設備を用いて高度な研究に取り組むことができます。卒業生は、群馬県内の製造業をはじめとする多様な分野で活躍しており、社会から高い評価を得ています。',
    },
    {
        id: 'tokyo',
        name: '東京工業高等専門学校',
        yomi: 'とうきょうこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '関東信越',
        website: 'https://www.tokyo-ct.ac.jp/',
        departments: ['機械工学科', '電気電子工学科', '情報工学科', '物質工学科'],
        description: '東京都八王子市に位置する国立高等専門学校。4つの専門学科があり、首都圏の産業を支える高度な技術者を育成。研究活動が活発で、多くの学生が学会で発表している。',
        latitude: 35.631,
        longitude: 139.289,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Tokyo_kousen_seimon.jpg',
        imageCreditText: 'Ishimochi, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Tokyo_kousen_seimon.jpg',
        detailedDescription: '東京工業高等専門学校は、1965年に設立された東京都八王子市に位置する国立高等専門学校です。「よく学び、よく考え、よく働き、国家、社会に貢献する」を教育目標に、創造性豊かな実践的技術者の育成を行っています。機械工学科、電気電子工学科、情報工学科、物質工学科の4学科を設置し、首都圏の多様な産業ニーズに応える高度な専門教育を提供しています。特に、学生による研究活動が非常に活発で、教員の指導のもと、早期から学会発表や論文執筆に挑戦する機会が豊富にあります。多くの研究学園都市である八王子市の立地を活かし、近隣の大学や研究機関、企業との連携も盛んです。卒業生は、大手企業の研究開発職や技術職に進む者も多く、その高い専門性と研究能力は産業界から高く評価されています。',
    },
    {
        id: 'tokyo-sangyo-gijutsu-shinagawa',
        name: '東京都立産業技術高等専門学校',
        yomi: 'とうきょうとりつさんぎょうぎじゅつこうとうせんもんがっこう',
        type: '公立',
        campus: '品川キャンパス',
        region: '関東信越',
        website: 'https://www.metro-cit.ac.jp/',
        departments: [
            'ものづくり工学科',
            '機械システム工学コース',
            '電気電子工学コース',
            'AI・情報システム工学コース',
        ],
        description: '東京都品川区にある公立高等専門学校。ものづくりを中心に、AIや情報システムなど最先端の技術を学ぶことができる。都心に位置し、企業との連携も活発。',
        latitude: 35.609,
        longitude: 139.743,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Advanced_Institute_of_Industrial_Technology_Shinagawa_Campus.jpg',
        imageCreditText: 'D2525, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Advanced_Institute_of_Industrial_Technology_Shinagawa_Campus.jpg',
        detailedDescription: '東京都立産業技術高等専門学校は、2006年に都立工業高専と都立航空高専を再編・統合して誕生した公立の高等専門学校です。品川キャンパスでは「ものづくり工学科」を設置し、機械システム工学、電気電子工学、AI・情報システム工学の3つのコースで、現代社会を支える基幹産業から最先端分野までを幅広くカバーしています。都心という立地を最大限に活かし、多くの企業や研究機関との連携プロジェクト、実践的なインターンシップが盛んに行われているのが大きな特徴です。特に、AIやIoT、ロボット技術などの次世代技術教育に力を入れており、社会の課題を解決できる創造性豊かな技術者の育成を目指しています。荒川キャンパスと連携し、文理融合の幅広い知識を学ぶことも可能です。',
    },
    {
        id: 'tokyo-sangyo-gijutsu-arakawa',
        name: '東京都立産業技術高等専門学校',
        yomi: 'とうきょうとりつさんぎょうぎじゅつこうとうせんもんがっこう',
        type: '公立',
        campus: '荒川キャンパス',
        region: '関東信越',
        website: 'https://www.metro-cit.ac.jp/',
        departments: [
            '航空宇宙工学科',
            'ロボット工学科',
            '医療福祉工学科',
            '生産システム工学科',
        ],
        description: '東京都荒川区にある公立高等専門学校。航空宇宙やロボット、医療福祉工学などユニークな分野を学べる。実践的なカリキュラムで、専門性の高い技術者を育成する。',
        latitude: 35.737,
        longitude: 139.809,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Tokyo_Metropolitan_College_of_Industrial_Technology_Arakawa_campus.jpg/1280px-Tokyo_Metropolitan_College_of_Industrial_Technology_Arakawa_campus.jpg',
        imageCreditText: 'Emotiile, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Tokyo_Metropolitan_College_of_Industrial_Technology_Arakawa_campus.jpg',
        detailedDescription: '東京都立産業技術高等専門学校の荒川キャンパスは、旧都立航空高専を母体とし、非常にユニークで専門性の高い教育を展開しています。航空宇宙工学、ロボット工学、医療福祉工学、生産システム工学の4つのコースを設置。特に、航空宇宙工学コースでは、航空機やロケットの設計・開発に関する専門知識を深く学べるなど、全国でも珍しいカリキュラムを提供しています。また、高齢化社会のニーズに応える医療福祉工学コースや、次世代の生産技術を担うロボット工学コースなど、未来の産業を創造するための教育に力を入れています。実験・実習を重視したカリキュラムと、学生一人ひとりに合わせた丁寧な指導が特徴です。品川キャンパスと連携し、幅広い工学分野の知識を学ぶことも可能で、専門性と複合的な視野を兼ね備えた技術者を目指せます。',
    },
    {
        id: 'nagaoka',
        name: '長岡工業高等専門学校',
        yomi: 'ながおかこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '関東信越',
        website: 'https://www.nagaoka-ct.ac.jp/',
        departments: [
            '機械工学科',
            '電気電子システム工学科',
            '電子制御工学科',
            '物質工学科',
            '環境都市工学科',
        ],
        description: '新潟県長岡市にある国立高等専門学校。5つの学科を擁し、ものづくりの町・長岡の技術を支える人材を育成。長岡技術科学大学への編入者が多いことでも知られる。',
        latitude: 37.409,
        longitude: 138.831,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/NNCT_2015.JPG',
        imageCreditText: 'D.suga, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:NNCT_2015.JPG',
        detailedDescription: '長岡工業高等専門学校は、1962年に設立された新潟県長岡市に位置する国立高等専門学校です。「人類の未来をきりひらく、たくましい実践的技術者の育成」を教育目標に掲げています。機械工学科、電気電子システム工学科、電子制御工学科、物質工学科、環境都市工学科の5つの専門学科を設置。日本有数のものづくりの街である長岡市の技術的基盤を支える人材を育成しています。最大の特徴は、すぐ近くに位置する長岡技術科学大学との緊密な連携です。多くの卒業生が同大学に編入学し、より高度な研究を続ける道が開かれています。この「高専と技科大の連携」は、技術者教育の一つのモデルケースとされています。学生の自主性を育むアクティブラーニングや、地域企業と連携した実践的な研究も盛んです。',
    },
    {
        id: 'nagano',
        name: '長野工業高等専門学校',
        yomi: 'ながのこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '関東信越',
        website: 'https://www.nagano-nct.ac.jp/',
        departments: ['工学科'],
        description: '長野県長野市に位置する国立高等専門学校。工学科に5つの専門コースを設置。情報技術や環境エネルギーなど、時代のニーズに合わせた教育を展開している。',
        detailedDescription: '長野工業高等専門学校は、1963年に設立された長野県長野市に位置する国立高等専門学校です。「共に学び、未来を拓く」をスローガンに、豊かな人間性と国際的な視野を持つ実践的技術者の育成を目指しています。工学科には、機械工学、電気電子工学、電子制御工学、電子情報工学、環境都市工学の5つのコースを設置。学生は2年次から各コースに分かれ、専門性を深めていきます。信州大学との連携が強く、教育・研究の両面で協力関係にあります。特に、大学の講義聴講や研究室での卒業研究などが可能で、高専にいながら大学レベルの学びに触れる機会が豊富です。また、地域産業界との連携も密接で、共同研究や技術相談、インターンシップなどを通じて、地域社会の発展に貢献しています。',
        latitude: 36.671,
        longitude: 138.243,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/National_Institute_of_Technology%2C_Nagano_College.JPG',
        imageCreditText: 'Rald, CC BY 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:National_Institute_of_Technology,_Nagano_College.JPG',
    },
    // 東海北陸地方
    {
        id: 'toyama-hongo',
        name: '富山高等専門学校',
        yomi: 'とやまこうとうせんもんがっこう',
        type: '国立',
        campus: '本郷キャンパス',
        region: '東海北陸',
        website: 'https://www.nc-toyama.ac.jp/',
        departments: [
            '機械システム工学科',
            '電気制御システム工学科',
            '物質化学工学科',
        ],
        description: '富山県富山市にある国立高等専門学校。本郷キャンパスは機械、電気、化学分野が中心。ものづくり教育に重点を置き、地域産業に貢献する技術者を育成している。',
        detailedDescription: '富山高等専門学校は、2009年に富山工業高等専門学校と富山商船高等専門学校が統合して誕生した高等専門学校です。本郷キャンパスは、旧富山工業高専を母体とし、工学分野の教育に重点を置いています。設置されているのは、機械システム工学科、電気制御システム工学科、物質化学工学科の3学科。それぞれの専門分野で基礎から応用までを体系的に学び、複合的な視点も養うことができます。特に「ものづくり教育」を教育の柱の一つに掲げ、実験・実習を重視したカリキュラムを通じて、創造性豊かな実践的技術者を育成。地域産業界との連携も密接で、共同研究やインターンシップなどを通じて、地域社会の発展に貢献する人材を輩出しています。',
        latitude: 36.698,
        longitude: 137.28,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Toyama-k%C5%8Dsen.JPG',
        imageCreditText: '越中掾, Public domain, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Toyama-k%C5%8Dsen.JPG?uselang=ja',
    },
    {
        id: 'toyama-imizu',
        name: '富山高等専門学校',
        yomi: 'とやまこうとうせんもんがっこう',
        type: '国立',
        campus: '射水キャンパス',
        region: '東海北陸',
        website: 'https://www.nc-toyama.ac.jp/',
        departments: [
            '電子情報工学科',
            '国際ビジネス学科',
            '商船学科',
            '情報工学・通信工学コース',
        ],
        description: '富山県射水市にある国立高等専門学校。情報、国際ビジネス、商船といった多様な学科を持つ。日本海側の重要港に位置し、海事教育や国際交流が盛ん。',
        detailedDescription: '富山高等専門学校の射水キャンパスは、旧富山商船高専を母体とし、工学、人文社会、商船学の3分野を学べるユニークな高等教育機関です。設置されているのは、電子情報工学科、国際ビジネス学科、そして航海士や機関士を養成する商船学科。これにより、技術者に必要な専門知識に加え、国際的なビジネス感覚や海事に関する高度な知識と技術を学ぶことができます。日本海に面した立地を活かし、練習船「若潮丸」を用いた航海実習など、実践的な海事教育が充実しています。また、国際交流も盛んで、グローバルな舞台で活躍できる人材の育成に力を入れています。',
        latitude: 36.772,
        longitude: 137.098,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Toyama_National_College_of_Maritime_Technology_Imizu_Campus_Main_Building_2018-04-28.jpg', // 404 Not Found
        imageCreditText: '掬茶, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Toyama_National_College_of_Maritime_Technology_Imizu_Campus_Main_Building_2018-04-28.jpg',
    },
    {
        id: 'ishikawa',
        name: '石川工業高等専門学校',
        yomi: 'いしかわこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '東海北陸',
        website: 'https://www.ishikawa-nct.ac.jp/',
        departments: [
            '機械工学科',
            '電気工学科',
            '電子情報工学科',
            '環境都市工学科',
            '建築学科',
        ],
        description: '石川県河北郡にある国立高等専門学校。5つの専門学科があり、幅広い工学分野を学ぶことができる。北陸の産業界と密接に連携し、実践力のある技術者を育成している。',
        detailedDescription: '石川工業高等専門学校は、1965年に設立された石川県河北郡に位置する国立高等専門学校です。「人間・社会・自然を理解し、創造性に富み、国際感覚を備えた実践的技術者の育成」を教育理念としています。機械工学科、電気工学科、電子情報工学科、環境都市工学科、建築学科の5つの専門学科を設置し、幅広い工学分野を網羅。各学科で基礎から応用までを体系的に学び、専門性を深めます。北陸地方の産業界との密接な連携を強みとし、インターンシップや共同研究などを通じて、現実の課題に触れる機会が豊富です。ものづくり教育にも力を入れており、学生の自主的な創造活動を支援しています。',
        latitude: 36.702,
        longitude: 136.71,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/34/Ishikawa-NCT_200509.jpg',
        imageCreditText: 'Tsql, CC0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Ishikawa-NCT_200509.jpg',
    },
    {
        id: 'fukui',
        name: '福井工業高等専門学校',
        yomi: 'ふくいこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '東海北陸',
        website: 'https://www.fukui-nct.ac.jp/',
        departments: ['創造工学科'],
        description: '福井県鯖江市にある国立高等専門学校。創造工学科に4つのコースを設置。地域産業の活性化に貢献することを目指し、企業との共同研究や課題解決型学習を推進している。',
        detailedDescription: '福井工業高等専門学校は、福井県鯖江市に位置する国立高等専門学校です。「自主・協調・創造」の校訓のもと、社会の変化に柔軟に対応できる技術者の育成を目指しています。2018年度に、従来の4学科を「創造工学科」1学科に再編し、機械工学、電気電子工学、物質工学、環境都市工学の4つの専門コースを設置しました。この体制により、学生は幅広い工学の基礎を学んだ上で、自身の興味や関心に応じて専門分野を深く探求できます。地域産業の活性化への貢献を重視しており、地元企業との共同研究や課題解決型学習（PBL）を積極的に推進。実践的なものづくりを通じて、問題解決能力と創造力を養います。',
        latitude: 35.986,
        longitude: 136.177,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/National_Institute_of_Technology%2C_Fukui_College_%28NIT-Fukui%29_1.jpg',
        imageCreditText: 'Ebiebi2, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:National_Institute_of_Technology,_Fukui_College_(NIT-Fukui)_1.jpg',
    },
    {
        id: 'gifu',
        name: '岐阜工業高等専門学校',
        yomi: 'ぎふこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '東海北陸',
        website: 'https://www.gifu-nct.ac.jp/',
        departments: [
            '機械工学科',
            '電気情報工学科',
            '電子制御工学科',
            '環境都市工学科',
            '建築学科',
        ],
        description: '岐阜県本巣市にある国立高等専門学校。5つの学科を有し、東海地方の「ものづくり」を支える中核的な技術者を育成。ロボットコンテストの強豪校としても知られている。',
        detailedDescription: '岐阜工業高等専門学校は、1963年に設立された岐阜県本巣市に位置する国立高等専門学校です。「知・徳・体の調和のとれた人間性豊かな技術者の育成」を教育目標に掲げています。機械工学科、電気情報工学科、電子制御工学科、環境都市工学科、建築学科の5学科を設置し、東海地方の基幹産業である「ものづくり」を支える中核的人材を育成。学生の自主性を尊重する校風で、特にロボットコンテストでは全国屈指の強豪校として知られ、毎年優れた成績を収めています。体験重視のカリキュラムと充実した設備を通じて、創造性と実践力を兼ね備えた技術者を目指せる環境が整っています。',
        latitude: 35.457,
        longitude: 136.69,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/%E6%AD%A3%E9%9D%A2%E7%8E%84%E9%96%A2%E4%BB%98%E8%BF%91%E3%81%8B%E3%82%89%E3%81%AE%E7%9C%BA%E3%82%81.JPG',
        imageCreditText: 'Level501, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:%E6%AD%A3%E9%9D%A2%E7%8E%84%E9%96%A2%E4%BB%98%E8%BF91%E3%81%8B%E3%82%89%E3%81%AE%E7%9C%BA%E3%82%81.JPG',
    },
    {
        id: 'numazu',
        name: '沼津工業高等専門学校',
        yomi: 'ぬまづこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '東海北陸',
        website: 'https://www.numazu-ct.ac.jp/',
        departments: [
            '機械工学科',
            '電気電子工学科',
            '電子制御工学科',
            '制御情報工学科',
            '物質工学科',
        ],
        description: '静岡県沼津市にある国立高等専門学校。5学科体制で、それぞれの専門性を深く追求できる。卒業生の多くが、静岡県内の主要企業で活躍している。',
        detailedDescription: '沼津工業高等専門学校は、1962年に設立された静岡県沼津市に位置する国立高等専門学校です。「自主・自律」の精神を尊重し、社会に貢献できる実践的技術者の育成を目指しています。機械工学科、電気電子工学科、電子制御工学科、制御情報工学科、物質工学科の5つの専門学科を設置し、それぞれの分野で高い専門性を追求できる教育体制を整えています。実験・実習を重視したカリキュラムで、理論と実践をバランスよく学びます。静岡県東部の工業地帯に位置し、地域産業界との連携も深く、卒業生の多くが県内の主要企業で技術者として活躍しており、その高い技術力は産業界から信頼されています。',
        latitude: 35.137,
        longitude: 138.894,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Numazu_National_College_of_Technology_20111126.jpg', // 404 Not Found
        imageCreditText: 'MASA, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Numazu_National_College_of_Technology_20111126.jpg',
    },
    {
        id: 'toyota',
        name: '豊田工業高等専門学校',
        yomi: 'とよたこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '東海北陸',
        website: 'https://www.toyota-ct.ac.jp/',
        departments: ['機械工学科', '電気・電子システム工学科', '情報工学科', '都市・建築工学科'],
        description: '愛知県豊田市にある国立高等専門学校。世界のトヨタのお膝元にあり、自動車産業をはじめとする地域の基幹産業を支える技術者を育成。企業との連携が非常に強い。',
        detailedDescription: '豊田工業高等専門学校は、1963年に設立された愛知県豊田市に位置する国立高等専門学校です。世界的な自動車産業の集積地である立地を最大限に活かし、「ものづくり」の中核を担う創造性豊かな実践的技術者の育成を目標としています。機械工学科、電気・電子システム工学科、情報工学科、都市・建築工学科の4学科を設置。特に自動車産業との連携は非常に強く、共同研究やインターンシップ、企業からの講師派遣などを通じて、学生は最先端の技術に触れる機会に恵まれています。卒業生はトヨタ自動車をはじめとする多くの企業で活躍しており、産業界から高い評価と信頼を得ています。',
        latitude: 35.084,
        longitude: 137.194,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Toyota_National_College_of_Technology_2.jpg', // 404 Not Found
        imageCreditText: 'Kouchi.commons, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Toyota_National_College_of_Technology_2.jpg',
    },
    {
        id: 'toba',
        name: '鳥羽商船高等専門学校',
        yomi: 'とばしょうせんこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '東海北陸',
        website: 'https://www.toba-cmt.ac.jp/',
        departments: ['商船学科', '電子機械工学科', '制御情報工学科'],
        description: '三重県鳥羽市にある国立の商船高等専門学校。航海士や機関士を養成する商船学科と、情報通信・メカトロニクス技術者を育成する学科を併設。長い歴史と伝統を持つ。',
        detailedDescription: '鳥羽商船高等専門学校は、1881年に起源を持つ日本で最も歴史のある商船教育機関の一つです。三重県の国際的な港湾都市、鳥羽市に位置しています。その長い歴史の中で、数多くの優秀な船員や技術者を輩出してきました。学科は、国際的な航路で活躍する航海士や機関士を育成する「商船学科」と、電子制御・情報通信・メカトロニクス技術を学ぶ「電子機械工学科」「制御情報工学科」で構成されています。最新のシミュレーターや実習設備が充実しており、理論と実践を融合させた教育が特徴です。また、練習船「鳥羽丸」を用いた実践的な航海実習も行われています。',
        latitude: 34.482,
        longitude: 136.843,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Toba_Shosen.jpg',
        imageCreditText: 'Miyuki Meinaka, CC0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Toba_Shosen.jpg',
    },
    {
        id: 'suzuka',
        name: '鈴鹿工業高等専門学校',
        yomi: 'すずかこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '東海北陸',
        website: 'https://www.suzuka-ct.ac.jp/',
        departments: [
            '機械工学科',
            '電気電子工学科',
            '電子情報工学科',
            '化学・生物応用工学科',
            '材料工学科',
        ],
        description: '三重県鈴鹿市にある国立高等専門学校。5つの学科を擁し、幅広い産業分野に対応できる技術者を育成。鈴鹿サーキットに近い立地から、モータースポーツ関連の研究も盛ん。',
        detailedDescription: '鈴鹿工業高等専門学校は、1962年に設立された三重県鈴鹿市に位置する国立高等専門学校です。「人類の福祉と世界の平和に貢献する」を理念に、豊かな人間性と創造性を備えた技術者を育成しています。機械工学科、電気電子工学科、電子情報工学科、化学・生物応用工学科、材料工学科の5学科を設置し、多様な産業分野のニーズに応える教育を展開。世界的に有名な鈴鹿サーキットに近いという立地を活かし、フォーミュラカーの開発プロジェクトなど、モータースポーツに関連したユニークな研究活動が盛んなことも大きな特徴です。学生が主体的にものづくりに取り組める環境が整っています。',
        latitude: 34.849219,
        longitude: 136.582231,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/16/The_main_gate_of_National_Institute_of_Technology%2C_Suzuka_college.jpg',
        imageCreditText: 'はまぐり, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:The_main_gate_of_National_Institute_of_Technology,_Suzuka_college.jpg',
    },
    // 近畿地方
    {
        id: 'maizuru',
        name: '舞鶴工業高等専門学校',
        yomi: 'まいづるこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '近畿',
        website: 'https://www.maizuru-ct.ac.jp/',
        departments: ['電子制御工学科', '建設システム工学科'],
        description: '京都府舞鶴市にある国立高等専門学校。2学科4コース制で、学生の興味や進路に応じた専門教育を実施。日本海に面した立地を活かし、海洋関連の研究も行われている。',
        detailedDescription: '舞鶴高専は、京都府舞鶴市に位置する国立高等専門学校です。「自主・自律」の精神を重んじ、創造性豊かな実践的技術者の育成を目指しています。2015年度に従来の学科を再編し、「電子制御工学科」と「建設システム工学科」を統合した「電子制御工学科」および「電気情報工学科」と「機械工学科」を統合した「機械工学科」の2学科体制となりました。各学科で専門性を深めるとともに、横断的な知識も習得できるカリキュラムが特徴です。国際交流にも積極的で、海外の大学との連携プログラムや留学生の受け入れを推進しており、グローバルな視野を養うことができます。日本海に面した自然豊かな環境で、のびのびと学習・研究に打ち込めるキャンパスです。',
        latitude: 35.485,
        longitude: 135.39,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/be/Maizuru_National_College_of_Technology.jpg',
        imageCreditText: 'Sea of Japan, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Maizuru_National_College_of_Technology.jpg',
    },
    {
        id: 'osaka',
        name: '大阪公立大学工業高等専門学校',
        yomi: 'おおさかこうりつだいがくこうぎょうこうとうせんもんがっこう',
        type: '公立',
        campus: '本校',
        region: '近畿',
        website: 'https://www.osaka-pct.ac.jp/',
        departments: ['総合工学システム学科'],
        description: '大阪府寝屋川市にある公立高等専門学校。大阪公立大学との連携により、高度な教育・研究環境を提供。1学科5コース制で、幅広い工学分野を学ぶことができる。',
        detailedDescription: '大阪公立大学工業高等専門学校は、2022年に大阪府立大学工業高等専門学校から名称変更された、大阪府寝屋川市に位置する公立の高等専門学校です。大阪公立大学との連携を強みとし、大学の施設利用や教員による授業など、高度な教育・研究環境が提供されています。「総合工学システム学科」1学科の中に、機械システム、メカトロニクス、電子情報、環境化学、都市環境の5つのコースを設置。幅広い工学分野を基礎から学び、3年次から専門コースに分かれて専門性を高めます。PBL型授業や卒業研究を通じて、社会の課題を解決できる創造性豊かな技術者の育成を目指しています。',
        latitude: 34.761,
        longitude: 135.617,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/47/OPUCT_Main_Gate.jpg', // 404 Not Found
        imageCreditText: 'OPUCT, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:OPUCT_Main_Gate.jpg',
    },
    {
        id: 'kobe',
        name: '神戸市立工業高等専門学校',
        yomi: 'こうべしりつこうぎょうこうとうせんもんがっこう',
        type: '公立',
        campus: '本校',
        region: '近畿',
        website: 'https://www.kobe-kosen.ac.jp/',
        departments: [
            '機械工学科',
            '電気工学科',
            '電子工学科',
            '応用化学科',
            '都市工学科',
        ],
        description: '兵庫県神戸市にある市立高等専門学校。5つの学科を擁し、神戸の産業を支える技術者を育成。ロボコンの強豪として全国的に有名で、実践的なものづくり教育に定評がある。',
        detailedDescription: '神戸市立工業高等専門学校は、1963年に設立された神戸市が設置する公立の高等専門学校です。「人間性豊かな、自律心と創造性に富む、実践的技術者の育成」を教育理念としています。機械工学科、電気工学科、電子工学科、応用化学科、都市工学科の5学科を設置し、神戸の多様な産業を支える人材を育成。特に、高専ロボットコンテストでは全国大会の常連であり、最多優勝記録を持つなど、全国屈指の強豪校としてその名を知られています。この実績に裏打ちされた、学生主体の実践的な「ものづくり教育」に定評があり、卒業生は産業界から高い評価を得ています。',
        latitude: 34.721,
        longitude: 135.152,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Kobe_City_College_of_Technology_201905_02.jpg', // 404 Not Found
        imageCreditText: 'Kobe City College of Technology, Public domain, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Kobe_City_College_of_Technology_201905_02.jpg',
    },
    {
        id: 'akashi',
        name: '明石工業高等専門学校',
        yomi: 'あかしこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '近畿',
        website: 'https://www.akashi.ac.jp/',
        departments: ['機械工学科', '電気情報工学科', '都市システム工学科', '建築学科'],
        description: '兵庫県明石市にある国立高等専門学校。4つの学科があり、幅広い工学分野の基礎から応用までを学ぶ。産業界からの高い評価を得ており、就職・進学ともに高い実績を誇る。',
        detailedDescription: '明石工業高等専門学校は、1963年に設立された兵庫県明石市に位置する国立高等専門学校です。「豊かな人間性と創造性を備え、社会の発展に貢献できる実践的技術者の育成」を目指しています。機械工学科、電気情報工学科、都市システム工学科、建築学科の4つの専門学科を設置。各分野で基礎から応用までを体系的に学べるカリキュラムが組まれています。実験・実習を重視し、理論を実践に結びつける能力を養います。産業界からの評価が非常に高く、就職率・求人倍率ともに常に高水準を維持しており、進学においても国公立の技術科学大学や主要大学への編入実績が豊富です。面倒見の良い教育体制にも定評があります。',
        latitude: 34.69,
        longitude: 134.957,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Akashi-nct-seimon.jpg', // 404 Not Found
        imageCreditText: 'Kinori, CC0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Akashi-nct-seimon.jpg',
    },
    {
        id: 'nara',
        name: '奈良工業高等専門学校',
        yomi: 'ならこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '近畿',
        website: 'https://www.nara-k.ac.jp/',
        departments: [
            '機械工学科',
            '電気工学科',
            '電子制御工学科',
            '情報工学科',
            '物質化学工学科',
        ],
        description: '奈良県大和郡山市にある国立高等専門学校。5学科体制で、各分野の専門家を育成。伝統文化の地、奈良にありながら、最先端の科学技術教育を行っている。',
        detailedDescription: '奈良工業高等専門学校は、1964年に設立された奈良県大和郡山市に位置する国立高等専門学校です。「社会に貢献する豊かな人間性を備えた創造的技術者の育成」を教育理念と掲げています。機械工学科、電気工学科、電子制御工学科、情報工学科、物質化学工学科の5学科を設置し、幅広い産業分野に対応できる人材を育成。古都奈良の歴史と文化に触れられる環境にありながら、最先端の科学技術を学ぶことができます。学生の自主性を育むPBL型授業や、きめ細やかな指導に力を入れています。高専ロボコンやプログラミングコンテストなどの全国大会でも優秀な成績を収めています。',
        latitude: 34.63,
        longitude: 135.776,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Nara_National_College_of_Technology.jpg', // 404 Not Found
        imageCreditText: 'Σ64, CC BY 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Nara_National_College_of_Technology.jpg',
    },
    {
        id: 'wakayama',
        name: '和歌山工業高等専門学校',
        yomi: 'わかやまこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '近畿',
        website: 'https://www.wakayama-nct.ac.jp/',
        departments: ['知能機械工学科', '電気情報工学科', '生物応用化学科', '環境都市工学科'],
        description: '和歌山県御坊市にある国立高等専門学校。4つの学科があり、地域産業のニーズに応える技術者を育成。災害に強いまちづくりなど、地域貢献型の研究も盛ん。',
        detailedDescription: '和歌山工業高等専門学校は、1964年に設立された和歌山県御坊市に位置する国立高等専門学校です。「優れた人格を備え、国際社会に貢献できる、創造性豊かな実践的技術者の育成」を目指しています。知能機械工学科、電気情報工学科、生物応用化学科、環境都市工学科の4つの専門学科を設置。それぞれの学科で特色ある教育を展開し、和歌山県の産業界や社会のニーズに応える人材を輩出しています。太平洋に面した立地から、防災・減災技術や環境エネルギーといった、地域課題の解決に直結する研究にも力を入れているのが特徴です。地域に根ざした実践的な技術者教育を行っています。',
        latitude: 33.882,
        longitude: 135.161,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Wakayama-nct-campus.jpg', // 404 Not Found
        imageCreditText: 'Kinori, CC0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Wakayama-nct-campus.jpg',
    },
    // 中国地方
    {
        id: 'tottori',
        name: '鳥取工業高等専門学校',
        yomi: 'とっとりこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '中国',
        website: 'https://www.tottori-nct.ac.jp/',
        departments: ['工学科'],
        description: '鳥取県米子市にある国立高等専門学校。1学科6コース制で、学生の多様な興味に対応。地域産業や医療との連携を深め、実践的な技術者を育成している。',
        detailedDescription: '鳥取工業高等専門学校は、鳥取県米子市に位置する国立高等専門学校で、旧米子工業高等専門学校を母体としています。「豊かな人間性と幅広い工学知識を基盤に、地域社会の発展に貢献できる実践的・創造的技術者の育成」を目指しています。2021年度に、従来の4学科を「工学科」1学科に再編し、その中に6つの専門コースを設置。学生は2年次からコースに分かれ、専門性を深めます。この体制により、複合的な分野への対応力を養います。特に、地域の医療機関や産業界との連携に力を入れており、医療工学分野や地域が抱える課題解決に取り組むPBL型授業などが特徴的です。',
        latitude: 35.419,
        longitude: 133.364,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Yonago_National_College_of_Technology_20111123.jpg', // 404 Not Found
        imageCreditText: 'MASA, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Yonago_National_College_of_Technology_20111123.jpg',
    },
    {
        id: 'matsue',
        name: '松江工業高等専門学校',
        yomi: 'まつえこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '中国',
        website: 'https://www.matsue-ct.ac.jp/',
        departments: ['機械工学科', '電気情報工学科', '電子制御工学科', '環境・建設工学科'],
        description: '島根県松江市にある国立高等専門学校。4学科を擁し、山陰地方の産業を支える技術者を育成。情報技術教育に力を入れており、プログラミングコンテストでの実績も豊富。',
        detailedDescription: '松江工業高等専門学校は、1964年に設立された島根県松江市に位置する国立高等専門学校です。「科学技術に関する専門的な知識・能力とともに、豊かな人間性を備えた、創造力ある実践的技術者の育成」を教育理念としています。機械工学科、電気情報工学科、電子制御工学科、環境・建設工学科の4学科を設置し、山陰地方の産業を支える人材を育成。特に情報技術教育に力を入れており、全国高専プログラミングコンテストでは数多くの受賞歴を誇る強豪校として知られています。学生の自主性を尊重し、PBL型授業や卒業研究を通じて、高度な問題解決能力を養います。',
        latitude: 35.453,
        longitude: 133.09,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Matsue_college.JPG', // 404 Not Found
        imageCreditText: 'Ki kurage, Public domain, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Matsue_college.JPG',
    },
    {
        id: 'tsuyama',
        name: '津山工業高等専門学校',
        yomi: 'つやまこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '中国',
        website: 'https://www.tsuyama-ct.ac.jp/',
        departments: ['総合理工学科'],
        description: '岡山県津山市にある国立高等専門学校。1学科4系で幅広い工学分野を網羅。少人数教育と丁寧な指導で、学生一人ひとりの能力を伸ばす教育を実践している。',
        detailedDescription: '津山工業高等専門学校は、1963年に設立された岡山県津山市に位置する国立高等専門学校です。「豊かな人間性と幅広い基礎学力をもち、専門分野における高い能力を身につけた、社会に貢献できる技術者の育成」を目指しています。2016年度に、従来の4学科を「総合理工学科」1学科に再編。その中に、先進科学、情報システム、機械システム、電気電子システムの4つの系を設置し、学生は3年次から各系に分かれます。この制度により、幅広い工学分野の基礎を学んだ上で専門性を追求できます。少人数教育による丁寧な指導が特徴で、学生一人ひとりの個性と能力を伸ばす教育を実践しています。',
        latitude: 35.086,
        longitude: 134.021,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Tsuyama_National_College_of_Technology.JPG', // 404 Not Found
        imageCreditText: 'Rs1421, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Tsuyama_National_College_of_Technology.JPG',
    },
    {
        id: 'kure',
        name: '呉工業高等専門学校',
        yomi: 'くれこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '中国',
        website: 'https://www.kure-nct.ac.jp/',
        departments: ['機械工学科', '電気情報工学科', '環境都市工学科', '建築学科'],
        description: '広島県呉市にある国立高等専門学校。「人間性に溢れ、創造性に富んだ、実践的技術者の育成」を教育理念とし、地域社会と連携した教育・研究活動を推進している。',
        detailedDescription: '呉工業高等専門学校は、広島県呉市に位置する国立高等専門学校です。1964年に設立され、長年にわたり産業界で活躍する多くの優れた技術者を輩出してきました。「人間性に溢れ、創造性に富んだ、実践的技術者の育成」を教育理念に掲げ、専門知識だけでなく、豊かな教養と倫理観を兼ね備えた人材の育成を目指しています。機械工学科、電気情報工学科、環境都市工学科、建築学科の4つの専門学科を設置し、各分野で地域社会と密接に連携した教育・研究活動を推進しています。インターンシップや共同研究を通じて、学生が実践的な問題解決能力を養う機会を豊富に提供しています。',
        latitude: 34.223889,
        longitude: 132.613333,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Kure_National_Colllege_Of_Technology_20200731.JPG',
        imageCreditText: 'Taisyo, CC BY 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Kure_National_Colllege_Of_Technology_20200731.JPG',
    },
    {
        id: 'tokuyama',
        name: '徳山工業高等専門学校',
        yomi: 'とくやまこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '中国',
        website: 'https://www.tokuyama.ac.jp/',
        departments: ['機械電気工学科', '情報電子工学科', '土木建築工学科'],
        description: '山口県周南市にある国立高等専門学校。3つの学科があり、周南コンビナートをはじめとする地域の産業界に多くの人材を輩出。実践的な技術教育に定評がある。',
        detailedDescription: '徳山工業高等専門学校は、1974年に設立された山口県周南市に位置する国立高等専門学校です。「豊かな人間性を涵養し、創造性に富む実践的技術者の育成」を目指しています。機械電気工学科、情報電子工学科、土木建築工学科の3つの学科を設置。各学科で複数の分野を融合した教育を行い、複合的な視点を持つ技術者を育成します。日本有数の石油化学コンビナートである周南コンビナートに隣接する立地を活かし、産業界との連携が非常に強いのが特徴です。企業との共同研究やインターンシップが盛んで、実践的な能力を養う機会に恵まれています。',
        latitude: 34.07,
        longitude: 131.815,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Tokuyama_College_of_Technology.jpg', // 404 Not Found
        imageCreditText: 'Σ64, CC BY 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Tokuyama_College_of_Technology.jpg',
    },
    {
        id: 'ube',
        name: '宇部工業高等専門学校',
        yomi: 'うべこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '中国',
        website: 'https://www.ube-k.ac.jp/',
        departments: [
            '機械工学科',
            '電気工学科',
            '制御情報工学科',
            '物質工学科',
            '経営情報学科',
        ],
        description: '山口県宇部市にある国立高等専門学校。工学系4学科に加え、文系の経営情報学科を持つ。技術と経営の両方の視点を持つ人材の育成を目指している。',
        detailedDescription: '宇部工業高等専門学校は、1962年に設立された山口県宇部市に位置する国立高等専門学校です。大きな特徴は、工学系の4学科（機械工学科、電気工学科、制御情報工学科、物質工学科）に加えて、文系学科である「経営情報学科」を設置している点です。これにより、技術的な専門知識と、経営学や情報科学、経済学などの知識を併せ持った、複合的な視野を持つ人材「テクノ・マネージャー」の育成を目指しています。学生の自主性を尊重する校風で、PBL型授業や地域連携活動を通じて、実践的な問題解決能力を養います。',
        latitude: 33.93,
        longitude: 131.268,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/72/Ube_Nat_Coll_of_Tech.JPG',
        imageCreditText: 'Wiki708, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Ube_Nat_Coll_of_Tech.JPG',
    },
    {
        id: 'oshima',
        name: '大島商船高等専門学校',
        yomi: 'おおしましょうせんこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '中国',
        website: 'https://www.oshima-k.ac.jp/',
        departments: ['商船学科', '電子機械工学科', '情報工学科'],
        description: '山口県大島郡にある国立の商船高専。商船学科と工学系2学科を併せ持つ。瀬戸内海の美しい島に位置し、海事教育と情報・メカトロニクス教育を行っている。',
        detailedDescription: '大島商船高等専門学校は、山口県大島郡周防大島町に位置する国立の商船高専です。航海士や機関士を養成する「商船学科」と、陸上のものづくりを担う「電子機械工学科」「情報工学科」を設置。海事教育と工学教育を融合させたユニークな教育を行っています。瀬戸内海の美しい自然に囲まれたキャンパスで、全寮制を基本とした人間教育にも力を入れています。練習船「大島丸」による長期の航海実習や、最新のシミュレータを用いた実践的な訓練が充実。グローバルな視野とリーダーシップを兼ね備え、海と陸の両分野で社会に貢献できる技術者の育成を目指しています。',
        latitude: 33.901,
        longitude: 132.391,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/74/Oshima_kousen_2.jpg',
        imageCreditText: 'Kiensvay, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Oshima_kousen_2.jpg',
    },
    // 四国地方
    {
        id: 'anan',
        name: '阿南工業高等専門学校',
        yomi: 'あなんこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '四国',
        website: 'https://www.anan-nct.ac.jp/',
        departments: ['創造技術工学科'],
        description: '徳島県阿南市にある国立高等専門学校。1学科4コース制で、幅広い工学分野をカバー。LED関連産業が集積する地域性を活かし、光技術に関する教育・研究が盛ん。',
        detailedDescription: '阿南工業高等専門学校は、1963年に設立された徳島県阿南市に位置する国立高等専門学校です。「創造性・人間性・国際性」を教育理念に掲げ、社会の多様な変化に対応できる技術者を育成しています。2016年度に、従来の4学科を「創造技術工学科」1学科に再編。機械、電気、制御情報、建設システムの4コースを設置し、学生は3年次から各コースに分かれて専門性を深めます。徳島県が世界的なLED関連産業の集積地であることから、光技術者やLED関連技術者を育成する「光・LEDコース」を設けるなど、地域産業と直結したユニークな教育が特徴です。',
        latitude: 33.9,
        longitude: 134.659,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Anan_National_College_of_Technology_20180415.jpg',
        imageCreditText: '掬茶, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Anan_National_College_of_Technology_20180415.jpg',
    },
    {
        id: 'kagawa',
        name: '香川高等専門学校',
        yomi: 'かがわこうとうせんもんがっこう',
        type: '国立',
        campus: '高松キャンパス',
        region: '四国',
        website: 'https://www.kagawa-nct.ac.jp/',
        departments: ['機械工学科', '電気情報工学科', '機械電子工学科', '建設環境工学科'],
        description: '香川県高松市にある国立高等専門学校。高松キャンパスは、機械、電気、情報、建設など基幹的な工学分野を担う。2キャンパス体制で四国の産業を支える。',
        detailedDescription: '香川高等専門学校は、2009年に高松工業高等専門学校と詫間電波工業高等専門学校が統合・再編して誕生した国立高等専門学校です。高松キャンパスは、旧高松高専を母体とし、基幹産業を支える工学分野の教育に重点を置いています。設置されているのは、機械工学科、電気情報工学科、機械電子工学科、建設環境工学科の4学科。それぞれの専門分野で体系的な教育を行い、ものづくりの基礎から応用までを学びます。詫間キャンパスと連携し、幅広い分野の知識を持つ技術者の育成を目指しています。地域産業界との連携も活発です。',
        latitude: 34.303,
        longitude: 134.088,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/27/Kagawa_National_College_of_Technology%2C_TAKAMATSU_CAMPUS_20180415.jpg', // 404 Not Found
        imageCreditText: '掬茶, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Kagawa_National_College_of_Technology,_TAKAMATSU_CAMPUS_20180415.jpg',
    },
    {
        id: 'kagawa-takamatsu',
        name: '香川高等専門学校',
        yomi: 'かがわこうとうせんもんがっこう',
        type: '国立',
        campus: '詫間キャンパス',
        region: '四国',
        website: 'https://www.kagawa-nct.ac.jp/',
        departments: ['電子システム工学科', '情報通信工学科', '情報工学科'],
        description: '香川県三豊市にある国立高等専門学校。詫間キャンパスは、通信・情報・エレクトロニクス分野に特化。電波関連の教育で長い歴史と実績を持つ。',
        detailedDescription: '香川高等専門学校の詫間キャンパスは、旧詫間電波高専を母体とし、情報通信技術（ICT）とエレクトロニクス分野に特化した教育を行っています。電子システム工学科、情報通信工学科、情報工学科の3学科を設置。電波技術の専門家を育成してきた長い歴史と伝統を強みとし、無線通信、ネットワーク、組込みシステムといった最先端のICT分野を深く学ぶことができます。高松キャンパスと連携し、ハードウェアとソフトウェアの両方に強い、社会のICT化を支える実践的な技術者を育成しています。自然豊かな環境で、落ち着いて学業に専念できるのも魅力です。',
        latitude: 34.225,
        longitude: 133.649,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Kagawa_National_College_of_Technology%2C_TAKUMA_CAMPUS_20180415.jpg/1280px-Kagawa_National_College_of_Technology%2C_TAKUMA_CAMPUS_20180415.jpg', // 404 Not Found
        imageCreditText: '掬茶, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Kagawa_National_College_of_Technology,_TAKUMA_CAMPUS_20180415.jpg',
    },
    {
        id: 'niihama',
        name: '新居浜工業高等専門学校',
        yomi: 'にいはまこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '四国',
        website: 'https://www.niihama-nct.ac.jp/',
        departments: [
            '機械工学科',
            '電気情報工学科',
            '電子制御工学科',
            '生物応用化学科',
            '環境材料工学科',
        ],
        description: '愛媛県新居浜市にある国立高等専門学校。四国を代表する工業地帯に位置し、地域の産業界と密接に連携。5つの専門学科で、高度な技術者を育成している。',
        detailedDescription: '新居浜工業高等専門学校は、1962年に設立された愛媛県新居浜市に位置する国立高等専門学校です。「優れた人格をもち、国際社会に貢献できる、創造性豊かな実践的技術者の育成」を教育目標としています。機械工学科、電気情報工学科、電子制御工学科、生物応用化学科、環境材料工学科の5学科を設置。四国を代表する工業都市である新居浜市の立地を活かし、地域の基幹産業と密接に連携した教育を展開しています。企業との共同研究やインターンシップが盛んで、学生は現実の課題に触れながら実践力を養うことができます。卒業生は地域産業界から高い評価を得ています。',
        latitude: 33.978,
        longitude: 133.308,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/38/Niihama_National_College_of_Technology.JPG', // 404 Not Found
        imageCreditText: 'Fffkk, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Niihama_National_College_of_Technology.JPG',
    },
    {
        id: 'yuge',
        name: '弓削商船高等専門学校',
        yomi: 'ゆげしょうせんこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '四国',
        website: 'https://www.yuge.ac.jp/',
        departments: ['商船学科', '電子機械工学科', '情報工学科'],
        description: '愛媛県越智郡にある国立の商船高専。瀬戸内海の芸予諸島に位置する。航海士・機関士を養成する商船学科と、情報・メカトロニクスを学ぶ工学科がある。',
        detailedDescription: '弓削商船高等専門学校は、愛媛県越智郡上島町の弓削島に位置する国立の商船高専です。「自主自律の精神に富み、心身ともに健全で、国際性に富んだ社会に貢献できる人材の育成」を目標としています。海のプロを育てる「商船学科」と、陸のエンジニアを育てる「電子機械工学科」「情報工学科」を設置。瀬戸内海の穏やかな海に囲まれた絶好のロケーションで、全寮制を基本とした教育を行っています。練習船「弓削丸」での航海実習やカッター訓練など、海事教育が充実しているのはもちろん、工学科でも実践的なものづくり教育に力を入れています。豊かな自然環境の中で、専門性と人間性を育みます。',
        latitude: 34.254,
        longitude: 133.203,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/53/Yuge_kousen.JPG',
        imageCreditText: 'Opqr, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Yuge_kousen.JPG',
    },
    {
        id: 'kochi',
        name: '高知工業高等専門学校',
        yomi: 'こうちこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '四国',
        website: 'https://www.kochi-ct.ac.jp/',
        departments: ['ソーシャルデザイン工学科'],
        description: '高知県南国市にある国立高等専門学校。1学科6コース制で、防災、地域活性化など社会課題の解決に貢献する技術者を育成。地域との連携を重視した教育が特徴。',
        detailedDescription: '高知工業高等専門学校は、1963年に設立された高知県南国市に位置する国立高等専門学校です。2016年度に、従来の5学科を「ソーシャルデザイン工学科」1学科に統合・再編したことが大きな特徴です。エネルギー、ロボティクス、情報、まちづくり、新素材、防災といった6つのコースを設置し、学生は3年次からコースを選択します。この体制により、専門性を持ちつつ、分野横断的な視点から社会課題の解決に貢献できる「Society 5.0」時代に対応した技術者の育成を目指しています。地域との連携を重視したPBL型授業や、防災・減災に関する研究が盛んです。',
        latitude: 33.585,
        longitude: 133.636,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Kochi_National_College_of_Technology_20111123.jpg', // 404 Not Found
        imageCreditText: 'MASA, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Kochi_National_College_of_Technology_20111123.jpg',
    },
    // 九州沖縄地方
    {
        id: 'kurume',
        name: '久留米工業高等専門学校',
        yomi: 'くるめこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '九州沖縄',
        website: 'https://www.kurume-nct.ac.jp/',
        departments: [
            '機械工学科',
            '電気電子工学科',
            '制御情報工学科',
            '生物応用化学科',
            '材料システム工学科',
        ],
        description: '福岡県久留米市にある国立高等専門学校。5つの学科を擁し、九州の「ものづくり」を支える人材を育成。自動車産業やバイオ産業との連携が強い。',
        detailedDescription: '久留米工業高等専門学校は、1964年に設立された福岡県久留米市に位置する国立高等専門学校です。「人間性の涵養、創造性の開発、将来性の啓発」を教育理念とし、社会に貢献できる技術者の育成を目指しています。機械工学科、電気電子工学科、制御情報工学科、生物応用化学科、材料システム工学科の5学科を設置。九州地方の主要産業である自動車産業や、地域の特色であるバイお産業との連携を強みとしています。企業との共同研究や実践的なインターンシップを通じて、最先端の技術に触れ、問題解決能力を養うことができます。',
        latitude: 33.287,
        longitude: 130.551,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Kurume_National_College_of_Technology.jpg', // 404 Not Found
        imageCreditText: 'Abasaa, Public domain, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Kurume_National_College_of_Technology.jpg',
    },
    {
        id: 'kitakyushu',
        name: '北九州工業高等専門学校',
        yomi: 'きたきゅうしゅうこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '九州沖縄',
        website: 'https://www.kct.ac.jp/',
        departments: ['生産デザイン工学科'],
        description: '福岡県北九州市にある国立高等専門学校。1学科5コース制で、多様な専門分野を学ぶことができる。北九州工業地帯に位置し、実践的な技術教育に定評がある。',
        detailedDescription: '北九州工業高等専門学校は、2017年に北九州高専と八幡高専が統合して誕生した国立高等専門学校です。「未来を拓く創造的な実践力を持つ技術者の育成」を教育目標に掲げています。大きな特徴は、従来の学科の枠を超えた「生産デザイン工学科」1学科5コース制です。機械、電気、制御、化学、土木建築の5つのコースがあり、学生は3年次からコースに分かれます。この体制により、複合的な視点とデザイン思考を身につけ、新たな価値を創造できる技術者を目指します。日本有数の工業地帯である北九州市の立地を活かし、産業界と密接に連携した実践的教育に定評があります。',
        latitude: 33.824,
        longitude: 130.767,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/18/Kitakyushu_National_College_of_Technology_20110526.jpg', // 404 Not Found
        imageCreditText: 'MASA, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Kitakyushu_National_College_of_Technology_20110526.jpg',
    },
    {
        id: 'fukuoka',
        name: '福岡工業高等専門学校',
        yomi: 'ふくおかこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '九州沖縄',
        website: 'https://www.fukuoka-ct.ac.jp/',
        departments: ['機械工学科', '電気工学科', '制御情報工学科', '化学工学科'],
        description: '福岡県福岡市にある国立高等専門学校。4学科を有し、九州最大の都市・福岡の産業を支える。IT分野やアジアとの国際交流に力を入れている。',
        detailedDescription: '有明工業高等専門学校は、福岡県大牟田市に位置する国立高等専門学校です。「人間性に富み、創造力のある実践的技術者の育成」を教育理念としています。機械工学科、電気工学科、制御情報工学科、化学工学科の4学科を設置し、九州の産業を支える人材を育成。エネルギー・環境・エレクトロニクス・バイオなどを重点分野とし、複合的な教育研究を推進しています。アジアに近いという地理的特性を活かし、留学生の受け入れや海外研修など国際交流が盛んです。地域企業との連携も深く、実践的なものづくり教育に力を入れています。',
        latitude: 33.593,
        longitude: 130.5,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Ariake_National_College_of_Technology.jpg', // 404 Not Found
        imageCreditText: 'Σ64, CC BY 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Ariake_National_College_of_Technology.jpg',
    },
    {
        id: 'sasebo',
        name: '佐世保工業高等専門学校',
        yomi: 'させぼこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '九州沖縄',
        website: 'https://www.sasebo.ac.jp/',
        departments: ['機械工学科', '電気電子工学科', '電子制御工学科', '物質工学科'],
        description: '長崎県佐世保市にある国立高等専門学校。4つの専門学科を設置。造船・国防の町、佐世保の技術的基盤を支え、実践力と創造性を兼ね備えた技術者を育成している。',
        detailedDescription: '佐世保工業高等専門学校は、1962年に設立された長崎県佐世保市に位置する国立高等専門学校です。「深く専門の学芸を教授し、職業に必要な能力を育成する」ことを目的としています。機械工学科、電気電子工学科、電子制御工学科、物質工学科の4つの専門学科を設置。古くから造船業で栄えた「ものづくりのまち」佐世保の技術的基盤を支えるべく、実験・実習を重視した実践的な技術教育を行っています。学生の自主性を育むアクティブラーニングやPBL型授業にも力を入れており、創造性豊かな技術者を育成。卒業生は地元の主要企業をはじめ、全国の産業界で活躍しています。',
        latitude: 33.141,
        longitude: 129.749,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Sasebo_National_College_of_Technology.jpg', // 404 Not Found
        imageCreditText: 'Los688, Public domain, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Sasebo_National_College_of_Technology.jpg',
    },
    {
        id: 'kumamoto',
        name: '熊本高等専門学校',
        yomi: 'くまもとこうとうせんもんがっこう',
        type: '国立',
        campus: '熊本キャンパス',
        region: '九州沖縄',
        website: 'https://www.knct.jp/',
        departments: [
            '情報通信エレクトロニクス工学科',
            '制御情報システム工学科',
            '人間情報システム工学科',
        ],
        description: '熊本県合志市にある国立高等専門学校。熊本キャンパスは情報・電気・電子分野に特化。半導体産業が集積する地域のニーズに応える人材を育成している。',
        detailedDescription: '熊本高等専門学校は、2009年に熊本電波工業高等専門学校と八代工業高等専門学校が統合・再編され誕生しました。熊本キャンパスは、旧熊本電波高専を母体とし、情報・電気・電子分野に特化した教育を行っています。情報通信エレクトロニクス工学科、制御情報システム工学科、人間情報システム工学科の3学科を設置。世界的な半導体産業の集積地である熊本の立地を活かし、半導体技術やICT、AIといった最先端分野で活躍できる人材の育成に力を入れています。八代キャンパスと連携し、幅広い知識を持つ技術者を目指せます。',
        latitude: 32.895,
        longitude: 130.771,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Kumamoto_National_College_of_Technology%2C_Yatsushiro_Campus_20180415.jpg', // 404 Not Found
        imageCreditText: '掬茶, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Kumamoto_National_College_of_Technology,_Yatsushiro_Campus_20180415.jpg',
    },
    {
        id: 'kumamoto-yatsushiro',
        name: '熊本高等専門学校',
        yomi: 'くまもとこうとうせんもんがっこう',
        type: '国立',
        campus: '八代キャンパス',
        region: '九州沖縄',
        website: 'https://www.knct.jp/',
        departments: [
            '機械知能システム工学科',
            '建築社会デザイン工学科',
            '生物化学システム工学科',
        ],
        description: '熊本県八代市にある国立高等専門学校。八代キャンパスは機械、建築、生物化学の3分野が中心。地域と連携し、複合的な課題解決能力を持つ技術者を育成する。',
        detailedDescription: '熊本高等専門学校の八代キャンパスは、旧八代高専を母体とし、機械、建築、生物化学といった基幹産業を支える分野の教育を行っています。機械知能システム工学科、建築社会デザイン工学科、生物化学システム工学科の3学科を設置。それぞれの専門分野を深く学ぶとともに、学科の枠を超えた融合教育にも力を入れています。地域との連携を重視し、地域の課題解決に取り組むPBL型授業や共同研究が盛んです。熊本キャンパスと連携し、複合的な視点と実践力を兼ね備えた技術者を育成しています。',
        latitude: 32.525,
        longitude: 130.63,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Kumamoto_National_College_of_Technology%2C_Yatsushiro_Campus_20180415.jpg', // 404 Not Found
        imageCreditText: '掬茶, CC BY-SA 4.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Kumamoto_National_College_of_Technology,_Yatsushiro_Campus_20180415.jpg',
    },
    {
        id: 'oita',
        name: '大分工業高等専門学校',
        yomi: 'おおいたこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '九州沖縄',
        website: 'https://www.oita-ct.ac.jp/',
        departments: ['機械工学科', '電気電子工学科', '情報工学科', '都市・環境工学科'],
        description: '大分県大分市にある国立高等専門学校。4つの学科を有し、大分県の産業振興に貢献。特に機械工学や情報工学の分野で高い評価を得ている。',
        detailedDescription: '大分工業高等専門学校は、1963年に設立された大分県大分市に位置する国立高等専門学校です。「人間性に富み、創造性に富んだ実践的技術者の育成」を教育理念としています。機械工学科、電気電子工学科、情報工学科、都市・環境工学科の4学科を設置。それぞれの専門分野で、基礎から応用まで体系的な教育を行っています。学生の自主的な学びを促すPBL型授業や卒業研究が活発で、ロボコンやプロコンなどの全国大会でも優秀な成績を収めています。大分県の産業振興に貢献する多くの技術者を輩出し、産業界から高い評価を得ています。',
        latitude: 33.197,
        longitude: 131.621,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Oita-nct.jpg', // 404 Not Found
        imageCreditText: 'Lover of Romance, Public domain, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Oita-nct.jpg',
    },
    {
        id: 'miyazaki',
        name: '都城工業高等専門学校',
        yomi: 'みやこのじょうこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '九州沖縄',
        website: 'https://www.miyakonojo-nct.ac.jp/',
        departments: ['機械工学科', '電気情報工学科', '物質工学科', '建築学科'],
        description: '宮崎県都城市にある国立高等専門学校。4つの学科を設置し、南九州の産業を支える技術者を育成。地域に根ざした教育と、グローバルな視野を持つ人材育成を両立している。',
        detailedDescription: '都城工業高等専門学校は、1964年に設立された宮崎県都城市に位置する国立高等専門学校です。「優れた人格を備え、社会に貢献できる、創造性豊かな実践的技術者の育成」を教育目標としています。機械工学科、電気情報工学科、物質工学科、建築学科の4学科を設置し、南九州の多様な産業ニーズに応える人材を育成。地域に根ざした教育を重視する一方、海外の大学との学術交流協定を結び、国際的に通用する技術者の育成にも力を入れています。きめ細やかな指導と、学生の主体性を尊重する教育に定評があります。',
        latitude: 31.748,
        longitude: 131.063,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Miyakonojo_National_College_of_Technology.jpg', // 404 Not Found
        imageCreditText: 'Fumihiko Ueno, CC BY 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Miyakonojo_National_College_of_Technology.jpg',
    },
    {
        id: 'kagoshima',
        name: '鹿児島工業高等専門学校',
        yomi: 'かごしまこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '九州沖縄',
        website: 'https://www.kagoshima-ct.ac.jp/',
        departments: [
            '機械工学科',
            '電気電子工学科',
            '電子制御工学科',
            '情報工学科',
            '都市環境デザイン工学科',
        ],
        description: '鹿児島県霧島市にある国立高等専門学校。5つの専門学科があり、幅広い工学分野をカバー。宇宙関連の研究や、再生可能エネルギーに関する取り組みが活発。',
        detailedDescription: '鹿児島工業高等専門学校は、1963年に設立された鹿児島県霧島市に位置する国立高等専門学校です。「社会の発展と人類の福祉に貢献できる、人間性・創造性豊かな実践的技術者の育成」を目指しています。機械工学科、電気電子工学科、電子制御工学科、情報工学科、都市環境デザイン工学科の5学科を設置。JAXA内之浦宇宙空間観測所に近いという地理的特性を活かし、航空宇宙工学に関する教育や研究が活発なことが大きな特徴です。また、再生可能エネルギーに関する取り組みにも力を入れています。地域に根ざしながら、宇宙まで視野に入れたユニークな教育を展開しています。',
        latitude: 31.761,
        longitude: 130.71,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Kagoshima_National_College_of_Technology.JPG', // 404 Not Found
        imageCreditText: 'Rs1421, CC BY-SA 3.0, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Kagoshima_National_College_of_Technology.JPG',
    },
    {
        id: 'okinawa',
        name: '沖縄工業高等専門学校',
        yomi: 'おきなわこうぎょうこうとうせんもんがっこう',
        type: '国立',
        campus: '本校',
        region: '九州沖縄',
        website: 'https://www.okinawa-ct.ac.jp/',
        departments: ['メディア情報工学科', '情報通信システム工学科', '生物資源工学科'],
        description: '沖縄県名護市にある日本最南端の国立高等専門学校。情報技術やバイオテクノロジーなど、沖縄の特性を活かしたユニークな教育・研究を展開している。',
        detailedDescription: '沖縄工業高等専門学校は、2004年に設立された日本で最も新しい国立高等専門学校であり、日本最南端に位置します。「豊かな人間性と創造的知性を備え、国際社会で活躍できる実践的技術者の育成」を教育理念としています。メディア情報工学科、情報通信システム工学科、生物資源工学科というユニークな3学科を設置。沖縄の亜熱帯性気候や生物多様性、アジアとの近接性といった地域の特性を最大限に活かし、IT、バイオテクノロジー、環境・エネルギー分野の教育・研究に力を入れているのが大きな特徴です。国際的な感性と地域貢献のマインドを併せ持つ人材を育成しています。',
        latitude: 26.577,
        longitude: 128.006,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Okinawa_National_College_of_Technology.jpg', // 404 Not Found
        imageCreditText: 'Don-V, Public domain, via Wikimedia Commons',
        imageCreditUrl: 'https://commons.wikimedia.org/wiki/File:Okinawa_National_College_of_Technology.jpg',
    },
];
